/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestaodefuncionariosdesupermercados;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Francisco Cordeiro
 */
public class AppGestaFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form AppGestaFuncionarios
     */
    public AppGestaFuncionarios() {
        this.fu = new Funcionarios();

        try {
            formatter1 = new MaskFormatter("#########");//nc
            formatter2 = new MaskFormatter("9########");//tele
            formatter3 = new MaskFormatter("PT50 #### #### ########### ##");//IBAN
        } catch (ParseException ex) {
            Logger.getLogger(AppGestaFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogInserirFunc = new javax.swing.JDialog();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEstatuto = new javax.swing.JLabel();
        jComboBoxEstatutos = new javax.swing.JComboBox<>();
        jLabelNúmeroDeContribuinte = new javax.swing.JLabel();
        jFormattedTextFieldNumContribuinte = new javax.swing.JFormattedTextField(formatter1);
        jLabelTelemovel = new javax.swing.JLabel();
        jFormattedTextFieldTelemovel = new javax.swing.JFormattedTextField(formatter2);
        jLabelIBAN = new javax.swing.JLabel();
        jFormattedTextFieldIBAN = new javax.swing.JFormattedTextField(formatter3);
        jLabelSalário = new javax.swing.JLabel();
        jLabelHoras = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jButtonInserir = new javax.swing.JButton();
        jTextFieldSalario = new javax.swing.JTextField();
        jDialogVerFuncionarios = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jButtonLimpar = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        jDialogVerTabelaDeFuncionarios = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jDialogPesquisaNome = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePesqNome = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuInserir = new javax.swing.JMenu();
        jMenuItemInserirFunc = new javax.swing.JMenuItem();
        jMenuVer = new javax.swing.JMenu();
        jMenuItemVerFuncionarios = new javax.swing.JMenuItem();
        jMenuItemVerTabela = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesqNome = new javax.swing.JMenuItem();

        jDialogInserirFunc.setTitle("Inserir Funcionarios");
        jDialogInserirFunc.setMinimumSize(new java.awt.Dimension(870, 570));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNome.setText("Nome:");

        jLabelEstatuto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEstatuto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelEstatuto.setText("Estatuto:");

        jLabelNúmeroDeContribuinte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNúmeroDeContribuinte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNúmeroDeContribuinte.setText("Número de Contribuinte:");

        jFormattedTextFieldNumContribuinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNumContribuinteActionPerformed(evt);
            }
        });

        jLabelTelemovel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelemovel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTelemovel.setText("Telemovel:");

        jLabelIBAN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIBAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIBAN.setText("IBAN:");
        jLabelIBAN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelSalário.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSalário.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalário.setText("Salário:");
        jLabelSalário.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelHoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHoras.setText("Horas:");
        jLabelHoras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorasActionPerformed(evt);
            }
        });

        jButtonInserir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogInserirFuncLayout = new javax.swing.GroupLayout(jDialogInserirFunc.getContentPane());
        jDialogInserirFunc.getContentPane().setLayout(jDialogInserirFuncLayout);
        jDialogInserirFuncLayout.setHorizontalGroup(
            jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogInserirFuncLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSalário)
                                    .addComponent(jLabelHoras)
                                    .addComponent(jLabelIBAN))
                                .addGap(128, 128, 128)
                                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNúmeroDeContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNome)
                                    .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldTelemovel, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                        .addGap(94, 94, 94))
                                    .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jComboBoxEstatutos, javax.swing.GroupLayout.Alignment.LEADING, 0, 181, Short.MAX_VALUE)
                                        .addComponent(jFormattedTextFieldNumContribuinte, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogInserirFuncLayout.setVerticalGroup(
            jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstatutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNúmeroDeContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldNumContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIBAN)
                    .addComponent(jFormattedTextFieldIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalário, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoras)
                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialogVerFuncionarios.setTitle("Ver Funcionarios");
        jDialogVerFuncionarios.setLocationByPlatform(true);
        jDialogVerFuncionarios.setMinimumSize(new java.awt.Dimension(891, 681));

        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jTextAreaOutput.setMinimumSize(new java.awt.Dimension(867, 611));
        jScrollPane1.setViewportView(jTextAreaOutput);

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setToolTipText("");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        Atualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogVerFuncionariosLayout = new javax.swing.GroupLayout(jDialogVerFuncionarios.getContentPane());
        jDialogVerFuncionarios.getContentPane().setLayout(jDialogVerFuncionariosLayout);
        jDialogVerFuncionariosLayout.setHorizontalGroup(
            jDialogVerFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogVerFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jDialogVerFuncionariosLayout.createSequentialGroup()
                        .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 578, Short.MAX_VALUE)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialogVerFuncionariosLayout.setVerticalGroup(
            jDialogVerFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogVerFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jDialogVerTabelaDeFuncionarios.setTitle("Tabela de Funcionarios");
        jDialogVerTabelaDeFuncionarios.setMinimumSize(new java.awt.Dimension(1110, 565));

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Estatuto", "Numero de Contribuinte", "Telemovel", "IBAN", "Horas feitas", "Salario", "Bonus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFuncionarios.setMinimumSize(new java.awt.Dimension(1183, 551));
        jScrollPane2.setViewportView(jTableFuncionarios);

        javax.swing.GroupLayout jDialogVerTabelaDeFuncionariosLayout = new javax.swing.GroupLayout(jDialogVerTabelaDeFuncionarios.getContentPane());
        jDialogVerTabelaDeFuncionarios.getContentPane().setLayout(jDialogVerTabelaDeFuncionariosLayout);
        jDialogVerTabelaDeFuncionariosLayout.setHorizontalGroup(
            jDialogVerTabelaDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerTabelaDeFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1183, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogVerTabelaDeFuncionariosLayout.setVerticalGroup(
            jDialogVerTabelaDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerTabelaDeFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogPesquisaNome.setTitle("Pesquisar por nome");
        jDialogPesquisaNome.setMinimumSize(new java.awt.Dimension(997, 776));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTablePesqNome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Estatuto", "Número de Contribuinte", "Telemovel", "IBAN", "Horas", "Sálario", "Bonus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablePesqNome);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogPesquisaNomeLayout = new javax.swing.GroupLayout(jDialogPesquisaNome.getContentPane());
        jDialogPesquisaNome.getContentPane().setLayout(jDialogPesquisaNomeLayout);
        jDialogPesquisaNomeLayout.setHorizontalGroup(
            jDialogPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPesquisaNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogPesquisaNomeLayout.setVerticalGroup(
            jDialogPesquisaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPesquisaNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestáo de Funcionarios");
        setMinimumSize(new java.awt.Dimension(943, 729));

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        jMenu1.setText("Aplicação");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenuInserir.setText("Inserir Tudo");

        jMenuItemInserirFunc.setText("Inserir Funcionarios");
        jMenuItemInserirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInserirFuncActionPerformed(evt);
            }
        });
        jMenuInserir.add(jMenuItemInserirFunc);

        jMenuBar1.add(jMenuInserir);

        jMenuVer.setText("Ver Tudo");

        jMenuItemVerFuncionarios.setText("Ver Funcionarios");
        jMenuItemVerFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerFuncionariosActionPerformed(evt);
            }
        });
        jMenuVer.add(jMenuItemVerFuncionarios);

        jMenuItemVerTabela.setText("Ver Tabela");
        jMenuItemVerTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerTabelaActionPerformed(evt);
            }
        });
        jMenuVer.add(jMenuItemVerTabela);

        jMenuBar1.add(jMenuVer);

        jMenuPesquisar.setText("Pesquisar Tudo");

        jMenuItemPesqNome.setText("Pesquisar Nome");
        jMenuItemPesqNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesqNomeActionPerformed(evt);
            }
        });
        jMenuPesquisar.add(jMenuItemPesqNome);

        jMenuBar1.add(jMenuPesquisar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemInserirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInserirFuncActionPerformed
        this.lerEstatutosBDJComboBox();
        jDialogInserirFunc.setVisible(true);
    }//GEN-LAST:event_jMenuItemInserirFuncActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        String nome = jTextFieldNome.getText();
        String estatuto = jComboBoxEstatutos.getSelectedItem().toString();
        String ncontribuinte = jFormattedTextFieldNumContribuinte.getText();
        String telemovel = jFormattedTextFieldTelemovel.getText();
        String iban = jFormattedTextFieldIBAN.getText();
        double salario = Double.parseDouble(jTextFieldSalario.getText());
        double horas = Double.parseDouble(jTextFieldHoras.getText());
        d.inserirFuncionarios(nome, estatuto, ncontribuinte, telemovel, iban, salario, horas);

        this.inserirDadosBD();
//        this.validaNif(ncontribuinte);
        this.limpaCampos();
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jMenuItemVerFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerFuncionariosActionPerformed
        jDialogVerFuncionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerFuncionariosActionPerformed

    private void jMenuItemVerTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerTabelaActionPerformed
        this.lerDadosTabela();
        jDialogVerTabelaDeFuncionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerTabelaActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextAreaOutput.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        this.lerBDTextArea();
    }//GEN-LAST:event_AtualizarActionPerformed

    private void jFormattedTextFieldNumContribuinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNumContribuinteActionPerformed
        
    }//GEN-LAST:event_jFormattedTextFieldNumContribuinteActionPerformed

    private void jTextFieldHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String nomep = jTextFieldNome.getText();
        String sql = "select * from Funcionarios where Nome like '"+nomep+"%'" ;
        lerTabelaNo(sql);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenuItemPesqNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesqNomeActionPerformed
//        this.lerDadosTabelaPsqNome();
        jDialogPesquisaNome.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesqNomeActionPerformed
    
    private void lerEstatutosBDJComboBox() {
        String url = "jdbc:sqlite:DBGestaoDeFuncionarios.db";
        Connection con;
        Statement stmt;
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppGestaFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from Estatutos order by Nome");

            jComboBoxEstatutos.removeAllItems();
            jComboBoxEstatutos.addItem("-- Escolha o estatuto --");
            while (rs.next()) {
                String estatuto = rs.getString("Nome");
                jComboBoxEstatutos.addItem(estatuto);
            }
            stmt.close();
            con.close();
        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
    }
    
    private void limpaCampos() {
        jTextFieldNome.setText("");
        jComboBoxEstatutos.setSelectedIndex(0);
        jFormattedTextFieldNumContribuinte.setText("");
        jFormattedTextFieldTelemovel.setText("");
        jFormattedTextFieldIBAN.setText("");
        jTextFieldSalario.setText("");
        jTextFieldHoras.setText("");
    }

    private void inserirDadosBD() {
        // Ler BD
        String url = "jdbc:sqlite:DBGestaoDeFuncionarios.db";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch (java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String nome = jTextFieldNome.getText();
            String estatuto = jComboBoxEstatutos.getSelectedItem().toString();
            int ncontribuinte = Integer.parseInt(jFormattedTextFieldNumContribuinte.getText());
            int telemovel = Integer.parseInt(jFormattedTextFieldTelemovel.getText());
            String iban = jFormattedTextFieldIBAN.getText();
            double salario = Double.parseDouble(jTextFieldSalario.getText());
            double horas = Double.parseDouble(jTextFieldHoras.getText());
            double bonus = (bonusPorHora());
            stmt.executeUpdate("Insert into Funcionarios" + " values('" + nome + "','" + estatuto + "'," + ncontribuinte + "," + telemovel + ",'" + iban + "'," + salario + "," + horas + "," + bonus + ")");

            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        // Fim LerBD
    }

//    public boolean validaNif(String nif) {
//        int max = 9;
////        nif = jFormattedTextFieldNumContribuinte.getText();
//        try {
//            if (!nif.matches("[0-9]") || nif.length() != max) {
//                return false;
//            }
//            int checkSum = 0;
//            //calcula a soma de controlo
//            for (int i = 0; i < max - 1; i++) {
//                checkSum += (nif.charAt(i) - '0') * (max - i);
//            }
//            int checkDigit = 11 - (checkSum % 11);
//            if (checkDigit >= 10) {
//                checkDigit = 0;
//            }
//            return checkDigit == nif.charAt(max - 1) - '0';
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(jFormattedTextFieldNumContribuinte, "Campo Vazio e incorreto!!!", e.getMessage(), JOptionPane.ERROR_MESSAGE);
//        }
//        return false;
//    }

    public void lerDadosTabela(){
        DefaultTableModel modelo = (DefaultTableModel) jTableFuncionarios.getModel();
        modelo.setRowCount(0);

        String url = "jdbc:sqlite:DBGestaoDeFuncionarios.db";
        Connection con;
        Statement stmt;
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String nomeTabela = "Funcionarios";
            ResultSet rs = stmt.executeQuery("select * from " + nomeTabela);

            while (rs.next()) {
                String nome = rs.getString("Nome");
                String estatuto = rs.getString("Estatuto");
                String ncontribuinte = rs.getString("Contribuinte");
                String telemovel = rs.getString("Telemovel");
                String iban =rs.getString("IBAN");
                String salario = rs.getString("Salário");
                String horas = rs.getString("Horas");
                double bonus = rs.getDouble("Bonus");
                Object[] rowData = {
                    nome,
                    estatuto,
                    ncontribuinte,
                    telemovel,
                    iban,
                    salario,
                    horas,
                    bonus
                };
                modelo.addRow(rowData);
                
            }
            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }  
    }
    
    public void lerDadosTabelaPsqNome(){
        DefaultTableModel modelo = (DefaultTableModel) jTablePesqNome.getModel();
        modelo.setRowCount(0);

        String url = "jdbc:sqlite:DBGestaoDeFuncionarios.db";
        Connection con;
        Statement stmt;
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String nomeTabela = "Funcionarios";
            ResultSet rs = stmt.executeQuery("select * from " + nomeTabela);

            while (rs.next()) {
                String nome = rs.getString("Nome");
                String estatuto = rs.getString("Estatuto");
                String ncontribuinte = rs.getString("Contribuinte");
                String telemovel = rs.getString("Telemovel");
                String iban =rs.getString("IBAN");
                String salario = rs.getString("Salário");
                String horas = rs.getString("Horas");
                double bonus = rs.getDouble("Bonus");
                Object[] rowData = {
                    nome,
                    estatuto,
                    ncontribuinte,
                    telemovel,
                    iban,
                    salario,
                    horas,
                    bonus
                };
                modelo.addRow(rowData);
            }
            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }  
    }
    
    private void lerBDTextArea() {
        String url = "jdbc:sqlite:DBGestaoDeFuncionarios.db";
        Connection con;
        Statement stmt;
        
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppGestaFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from Funcionarios order by nome");
            
            while (rs.next()) {
                String nome = rs.getString("Nome");
                String estatuto = rs.getString("Estatuto");
                String ncontribuinte = rs.getString("Contribuinte");
                String telemovel = rs.getString("Telemovel");
                String iban =rs.getString("IBAN");
                String salario = rs.getString("Salário");
                String horas = rs.getString("Horas");
                double bonus = rs.getDouble("Bonus");
                jTextAreaOutput.append(   "Nome: "+nome+"\n"
                                        + "Estatuto: "+estatuto+"\n"
                                        + "Número de Contribuinte: "+ncontribuinte+"\n"
                                        + "Telemovel: "+telemovel+"\n"
                                        + "IBAN: "+iban+"\n"
                                        + "Salário: "+salario+"\n"
                                        + "Horas:"+horas+"\n"
                                        + "Salário com Bonus: "+bonus+"\n"
                                        + "-----------------------------------------\n"); 
            }
            
            stmt.close();
            con.close();
        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
    }
    
    public double bonusPorHora() {     
        bonusHora = 5.0 *(Double.parseDouble(jTextFieldHoras.getText()));
        salarioTotal = (Double.parseDouble(jTextFieldSalario.getText())) + bonusHora;
        return salarioTotal;
    }
    
    private void lerTabelaNo(String sql){
        String url = "jdbc:sqlite:DBGestaoDeFuncionarios.db";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch(java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            DefaultTableModel modelo = (DefaultTableModel)jTablePesqNome.getModel();
            modelo.setRowCount(0);
            while (rs.next()) {	
            	String nome = rs.getString("Nome");
                String estatuto = rs.getString("Estatuto");
                String ncontribuinte = rs.getString("Contribuinte");
                String telemovel = rs.getString("Telemovel");
                String iban =rs.getString("IBAN");
                String salario = rs.getString("Salário");
                String horas = rs.getString("Horas");
                double bonus = rs.getDouble("Bonus");
                Object [] dados ={ 
                    nome,
                    estatuto,
                    ncontribuinte,
                    telemovel,
                    iban,
                    salario,
                    horas,
                    bonus
                };
                modelo.addRow(dados);
            }
            stmt.close();
            con.close();

        } catch(SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGestaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGestaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGestaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGestaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AppGestaFuncionarios().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox<String> jComboBoxEstatutos;
    private javax.swing.JDialog jDialogInserirFunc;
    private javax.swing.JDialog jDialogPesquisaNome;
    private javax.swing.JDialog jDialogVerFuncionarios;
    private javax.swing.JDialog jDialogVerTabelaDeFuncionarios;
    private javax.swing.JFormattedTextField jFormattedTextFieldIBAN;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumContribuinte;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelemovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEstatuto;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelIBAN;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNúmeroDeContribuinte;
    private javax.swing.JLabel jLabelSalário;
    private javax.swing.JLabel jLabelTelemovel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInserir;
    private javax.swing.JMenuItem jMenuItemInserirFunc;
    private javax.swing.JMenuItem jMenuItemPesqNome;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVerFuncionarios;
    private javax.swing.JMenuItem jMenuItemVerTabela;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTable jTablePesqNome;
    private javax.swing.JTextArea jTextAreaOutput;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables

    GestaoFuncionarios d = new GestaoFuncionarios();
    Funcionarios fu;
    MaskFormatter formatter1;
    MaskFormatter formatter2;
    MaskFormatter formatter3;
    private double bonusHora = 0;
    private double salarioTotal = 0; 
    
}
