/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestaodefuncionariosdesupermercados;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Francisco Cordeiro
 */
public class AppGestaFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form AppGestaFuncionarios
     */
    public AppGestaFuncionarios() {
        this.fun = new Funcionarios();

        try {
            formatter1 = new MaskFormatter("#########");//nc
            formatter2 = new MaskFormatter("9########");//tele
            formatter3 = new MaskFormatter("PT50 #### #### ########### ##");//IBAN
        } catch (ParseException ex) {
            Logger.getLogger(AppGestaFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogInserirFunc = new javax.swing.JDialog();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEstatuto = new javax.swing.JLabel();
        jComboBoxEstatutos = new javax.swing.JComboBox<>();
        jLabelNúmeroDeContribuinte = new javax.swing.JLabel();
        jFormattedTextFieldNumContribuinte = new javax.swing.JFormattedTextField(formatter1);
        jLabelTelemovel = new javax.swing.JLabel();
        jFormattedTextFieldTelemovel = new javax.swing.JFormattedTextField(formatter2);
        jLabelIBAN = new javax.swing.JLabel();
        jFormattedTextFieldIBAN = new javax.swing.JFormattedTextField(formatter3);
        jLabelSalário = new javax.swing.JLabel();
        jLabelHoras = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jButtonInserir = new javax.swing.JButton();
        jTextFieldSalario = new javax.swing.JTextField();
        jDialogVerFuncionarios = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jButtonLimpar = new javax.swing.JButton();
        Atualizar = new javax.swing.JButton();
        jDialogVerTabelaDeFuncionarios = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuInserir = new javax.swing.JMenu();
        jMenuItemInserirFunc = new javax.swing.JMenuItem();
        jMenuVer = new javax.swing.JMenu();
        jMenuItemVerFuncionarios = new javax.swing.JMenuItem();
        jMenuItemVerTabela = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesqNome = new javax.swing.JMenuItem();

        jDialogInserirFunc.setTitle("Inserir Funcionarios");
        jDialogInserirFunc.setMinimumSize(new java.awt.Dimension(870, 570));

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("Nome:");

        jLabelEstatuto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEstatuto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstatuto.setText("Estatuto:");

        jLabelNúmeroDeContribuinte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNúmeroDeContribuinte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNúmeroDeContribuinte.setText("Número de Contribuinte:");

        jFormattedTextFieldNumContribuinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNumContribuinteActionPerformed(evt);
            }
        });

        jLabelTelemovel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelemovel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelemovel.setText("Telemovel:");

        jLabelIBAN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIBAN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIBAN.setText("IBAN:");
        jLabelIBAN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelSalário.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSalário.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalário.setText("Salário:");
        jLabelSalário.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelHoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHoras.setText("Horas:");
        jLabelHoras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonInserir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonInserir.setText("Inserir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogInserirFuncLayout = new javax.swing.GroupLayout(jDialogInserirFunc.getContentPane());
        jDialogInserirFunc.getContentPane().setLayout(jDialogInserirFuncLayout);
        jDialogInserirFuncLayout.setHorizontalGroup(
            jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogInserirFuncLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                                .addComponent(jLabelEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxEstatutos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSalário)
                                    .addComponent(jLabelIBAN)
                                    .addComponent(jLabelHoras))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                                .addComponent(jLabelTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                                .addComponent(jLabelNúmeroDeContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldNumContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogInserirFuncLayout.setVerticalGroup(
            jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogInserirFuncLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstatuto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstatutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNúmeroDeContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldNumContribuinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIBAN)
                    .addComponent(jFormattedTextFieldIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalário)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jDialogInserirFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoras)
                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialogVerFuncionarios.setTitle("Ver Funcionarios");
        jDialogVerFuncionarios.setMinimumSize(new java.awt.Dimension(836, 638));

        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jTextAreaOutput.setMinimumSize(new java.awt.Dimension(816, 538));
        jScrollPane1.setViewportView(jTextAreaOutput);

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setToolTipText("");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        Atualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogVerFuncionariosLayout = new javax.swing.GroupLayout(jDialogVerFuncionarios.getContentPane());
        jDialogVerFuncionarios.getContentPane().setLayout(jDialogVerFuncionariosLayout);
        jDialogVerFuncionariosLayout.setHorizontalGroup(
            jDialogVerFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogVerFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addGroup(jDialogVerFuncionariosLayout.createSequentialGroup()
                        .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDialogVerFuncionariosLayout.setVerticalGroup(
            jDialogVerFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogVerFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(Atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDialogVerTabelaDeFuncionarios.setTitle("Tabela de Funcionarios");

        javax.swing.GroupLayout jDialogVerTabelaDeFuncionariosLayout = new javax.swing.GroupLayout(jDialogVerTabelaDeFuncionarios.getContentPane());
        jDialogVerTabelaDeFuncionarios.getContentPane().setLayout(jDialogVerTabelaDeFuncionariosLayout);
        jDialogVerTabelaDeFuncionariosLayout.setHorizontalGroup(
            jDialogVerTabelaDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogVerTabelaDeFuncionariosLayout.setVerticalGroup(
            jDialogVerTabelaDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestáo de Funcionarios");
        setMinimumSize(new java.awt.Dimension(943, 729));

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

        jMenu1.setText("Aplicação");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenuInserir.setText("Inserir Tudo");

        jMenuItemInserirFunc.setText("Inserir Funcionarios");
        jMenuItemInserirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInserirFuncActionPerformed(evt);
            }
        });
        jMenuInserir.add(jMenuItemInserirFunc);

        jMenuBar1.add(jMenuInserir);

        jMenuVer.setText("Ver Tudo");

        jMenuItemVerFuncionarios.setText("Ver Funcionarios");
        jMenuItemVerFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerFuncionariosActionPerformed(evt);
            }
        });
        jMenuVer.add(jMenuItemVerFuncionarios);

        jMenuItemVerTabela.setText("Ver Tabela");
        jMenuItemVerTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerTabelaActionPerformed(evt);
            }
        });
        jMenuVer.add(jMenuItemVerTabela);

        jMenuBar1.add(jMenuVer);

        jMenuPesquisar.setText("Pesquisar Tudo");

        jMenuItemPesqNome.setText("Pesquisar Nome");
        jMenuPesquisar.add(jMenuItemPesqNome);

        jMenuBar1.add(jMenuPesquisar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemInserirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInserirFuncActionPerformed
        this.lerEstatutosBDJComboBox();
        jDialogInserirFunc.setVisible(true);
    }//GEN-LAST:event_jMenuItemInserirFuncActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        String nome = jTextFieldNome.getText();
        String estatuto = jComboBoxEstatutos.getSelectedItem().toString();
        String ncontribuinte = jFormattedTextFieldNumContribuinte.getText();
        String telemovel = jFormattedTextFieldTelemovel.getText();
        String iban = jFormattedTextFieldIBAN.getText();
        double salario = Double.parseDouble(jTextFieldSalario.getText());
        double horas = Double.parseDouble(jTextFieldHoras.getText());
        d.inserirFuncionarios(nome, estatuto, ncontribuinte, telemovel, iban, salario, horas);

        this.inserirDadosBD();

        this.limpaCampos();
    }//GEN-LAST:event_jButtonInserirActionPerformed

    private void jMenuItemVerFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerFuncionariosActionPerformed
        jDialogVerFuncionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerFuncionariosActionPerformed

    private void jMenuItemVerTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerTabelaActionPerformed
//        DefaultTableModel modelo = (DefaultTableModel) jTableFuncionarios.getModel();
//        modelo.setRowCount(0);
//        ArrayList<GestaoTodos> t = f.gettTodos();
//        for (GestaoTodos a : t) {
//            Object[] rowData = {
//                a.getNome(),
//                a.getEstatuto(),
//                a.getNcontribuinte(),
//                a.getTelemovel(),
//                a.getIBAN(),
//                a.getSalario(),
//                a.getHoras()
//            };
//            modelo.addRow(rowData);
//        }
//        jDialogVerTabelaDeFuncionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerTabelaActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextAreaOutput.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        jTextAreaOutput.append(d.verTodos());
    }//GEN-LAST:event_AtualizarActionPerformed

    private void jFormattedTextFieldNumContribuinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNumContribuinteActionPerformed
        
    }//GEN-LAST:event_jFormattedTextFieldNumContribuinteActionPerformed

    private void lerEstatutosBDJComboBox() {
        String url = "jdbc:sqlite:DBGestaoDeFuncionarios.db";
        Connection con;
        Statement stmt;
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppGestaFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from Estatutos order by Nome");

            jComboBoxEstatutos.removeAllItems();
            jComboBoxEstatutos.addItem("-- Escolha o estatuto --");
            while (rs.next()) {
                String estatuto = rs.getString("Nome");
                jComboBoxEstatutos.addItem(estatuto);
            }
            stmt.close();
            con.close();
        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
    }

    private void limpaCampos() {
        jTextFieldNome.setText("");
        jComboBoxEstatutos.setSelectedIndex(0);
        jFormattedTextFieldNumContribuinte.setText("");
        jFormattedTextFieldTelemovel.setText("");
        jFormattedTextFieldIBAN.setText("");
        jTextFieldSalario.setText("");
        jTextFieldHoras.setText("");
    }

    private void inserirDadosBD() {
        // Ler BD
        String url = "jdbc:sqlite:DBGestaoDeFuncionarios.db";
        Connection con;
        Statement stmt;

        try {
            Class.forName("org.sqlite.JDBC");
        } catch (java.lang.ClassNotFoundException e) {
            System.err.print("ClassNotFoundException: ");
            System.err.println(e.getMessage());
        }

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String nome = jTextFieldNome.getText();
            String estatuto = jComboBoxEstatutos.getSelectedItem().toString();
            int ncontribuinte = Integer.parseInt(jFormattedTextFieldNumContribuinte.getText());
            int telemovel = Integer.parseInt(jFormattedTextFieldTelemovel.getText());
            String iban = jFormattedTextFieldIBAN.getText();
            double salario = Double.parseDouble(jTextFieldSalario.getText());
            double horas = Double.parseDouble(jTextFieldHoras.getText());
            d.inserirFuncionarios(nome, estatuto, iban, nome, iban, salario, horas);
            double salariocombonus = (fun.bonusPorHora());
            stmt.executeUpdate("Insert into Funcionarios" + " values('" + nome + "','" + estatuto + "'," + ncontribuinte + "," + telemovel + ",'" + iban + "'," + salario + "," + horas + "," + salariocombonus + ")");

            stmt.close();
            con.close();

        } catch (SQLException ex) {
            System.err.println("SQLException: " + ex.getMessage());
        }
        // Fim LerBD
    }

    public boolean validaNif(String nif) {

        nif = jFormattedTextFieldNumContribuinte.getText();
        try {
            final int max = 9;
            if (!nif.matches("[0-9]+") || nif.length() != max) {
                return false;
            }
            int checkSum = 0;
            //calcula a soma de controlo
            for (int i = 0; i < max - 1; i++) {
                checkSum += (nif.charAt(i) - '0') * (max - i);
            }
            int checkDigit = 11 - (checkSum % 11);
            if (checkDigit >= 10) {
                checkDigit = 0;
            }
            return checkDigit == nif.charAt(max - 1) - '0';
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jFormattedTextFieldNumContribuinte, e, nif, JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGestaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGestaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGestaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGestaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGestaFuncionarios().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox<String> jComboBoxEstatutos;
    private javax.swing.JDialog jDialogInserirFunc;
    private javax.swing.JDialog jDialogVerFuncionarios;
    private javax.swing.JDialog jDialogVerTabelaDeFuncionarios;
    private javax.swing.JFormattedTextField jFormattedTextFieldIBAN;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumContribuinte;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelemovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEstatuto;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelIBAN;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNúmeroDeContribuinte;
    private javax.swing.JLabel jLabelSalário;
    private javax.swing.JLabel jLabelTelemovel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInserir;
    private javax.swing.JMenuItem jMenuItemInserirFunc;
    private javax.swing.JMenuItem jMenuItemPesqNome;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemVerFuncionarios;
    private javax.swing.JMenuItem jMenuItemVerTabela;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOutput;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables

    GestaoFuncionarios d = new GestaoFuncionarios();
    Funcionarios fun;
    MaskFormatter formatter1;
    MaskFormatter formatter2;
    MaskFormatter formatter3;
}
